### ISSUE TITLE
Integration with WHMCS Shopping Cart

### ISSUE THREAD

**Issue by tarundeology** [webtechfreaky/Cloud-Pricing-Slider#2]
Hello,

Is it possible to integrate with WHMCS?

**Comment by InDirectVariant** [comment]
You can always take the product link and insert it into each 'Buy' button. Not sure if it's able to integrate though.

**Comment by tarundeology** [comment]
I'll try that. Thanks.

**Comment by InDirectVariant** [comment]
It worked when I had done it. Good luck!
